/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import communication.Communication;
import domain.*;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class PretragaFilmaForma extends javax.swing.JDialog {

    /**
     * Creates new form PretragaFilmaForma
     */
    public PretragaFilmaForma(JDialog owner) {
        super(owner);
        initComponents();
        setLocationRelativeTo(null);
        prepareView();

    }

    public PretragaFilmaForma(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        setLocationRelativeTo(null);
        btnIzaberiFilm.setVisible(false);
        listMovie.setEnabled(false);
       // listMovie.setForeground(Color.PINK);
      // listMovie.setFont(new Font("Segoe UI", Font.BOLD, 12));
    
        prepareView();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbdZanr = new javax.swing.JComboBox();
        cbdReziser = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnReziser = new javax.swing.JButton();
        btnZanr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMovie = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        btnNaziv = new javax.swing.JButton();
        btnIzaberiFilm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretraga filmova", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N

        jLabel1.setText("Pretrazi po žanru: ");

        cbdZanr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbdReziser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Pretrazi po režiseru: ");

        btnReziser.setText("Pretrazi");
        btnReziser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReziserActionPerformed(evt);
            }
        });

        btnZanr.setText("Pretrazi");
        btnZanr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZanrActionPerformed(evt);
            }
        });

        listMovie.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMovie);

        jLabel3.setText("Pretrazi po nazivu: ");

        btnNaziv.setText("Pretrazi");
        btnNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazivActionPerformed(evt);
            }
        });

        btnIzaberiFilm.setText("Izaberi film");
        btnIzaberiFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiFilmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzaberiFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv)
                            .addComponent(cbdZanr, 0, 623, Short.MAX_VALUE)
                            .addComponent(cbdReziser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnZanr))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReziser)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbdZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbdReziser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnReziser))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNaziv)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnZanr)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnIzaberiFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReziserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReziserActionPerformed

        Reziser reziser = (Reziser) cbdReziser.getSelectedItem();
        Film film=new Film(Long.MIN_VALUE, null, null, Integer.MIN_VALUE, null, null, null, reziser, null);
        try {
            List<Film> filmovi = Communication.getInstance().findMovies(film);
            if(filmovi.isEmpty())
                JOptionPane.showMessageDialog(this, "Nema filmova za zadati kriterijum pretrage!");
            else
                listMovie.setListData(filmovi.toArray());
        } catch (Exception ex) {
            Logger.getLogger(PretragaFilmaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnReziserActionPerformed

    private void btnZanrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZanrActionPerformed

        Zanr zanr = (Zanr) cbdZanr.getSelectedItem();
        try {
              Film film=new Film(Long.MIN_VALUE, null, null, Integer.MIN_VALUE, null, null, zanr, null, null);
            List<Film> filmovi = Communication.getInstance().findMovies(film);
            if(filmovi.isEmpty())
                JOptionPane.showMessageDialog(this, "Nema filmova za zadati kriterijum pretrage!");
            else
                listMovie.setListData(filmovi.toArray());
        } catch (Exception ex) {
            Logger.getLogger(PretragaFilmaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnZanrActionPerformed

    private void btnNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazivActionPerformed
        String naziv = txtNaziv.getText().trim();
        try {
            
            Film film=new Film(Long.MIN_VALUE, naziv, null, Integer.MIN_VALUE, null, null, null, null, null);
            List<Film> filmovi = Communication.getInstance().findMovies(film);
            if(filmovi.isEmpty())
                JOptionPane.showMessageDialog(this, "Nema filmova za zadati kriterijum pretrage!");
            else
                listMovie.setListData(filmovi.toArray());

        } catch (Exception ex) {
            Logger.getLogger(PretragaFilmaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNazivActionPerformed

    private void btnIzaberiFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiFilmActionPerformed
        KreirajRecenzijuForma rf=(KreirajRecenzijuForma) getOwner();
        Film film=(Film) listMovie.getSelectedValue();
        rf.setFilm(film);
        this.dispose();
    }//GEN-LAST:event_btnIzaberiFilmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaFilmaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaFilmaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaFilmaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaFilmaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberiFilm;
    private javax.swing.JButton btnNaziv;
    private javax.swing.JButton btnReziser;
    private javax.swing.JButton btnZanr;
    private javax.swing.JComboBox cbdReziser;
    private javax.swing.JComboBox cbdZanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listMovie;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        try {
            List<Zanr> zanrovi = Communication.getInstance().getZanrovi();
            List<Reziser> reziseri = Communication.getInstance().getReziseri();
            cbdReziser.removeAllItems();
            cbdZanr.removeAllItems();
            for (Zanr zanr : zanrovi) {
                cbdZanr.addItem(zanr);
            }
            for (Reziser reziser : reziseri) {
                cbdReziser.addItem(reziser);
            }
            listMovie.setListData(new Object[0]);
            
        } catch (Exception ex) {
            Logger.getLogger(KreirajFilmForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
