/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formFilm;

import communication.Communication;
import domain.Film;
import domain.Glumac;
import domain.Reziser;
import domain.Zanr;
import formLista.KreiranjeListeForma;
import form.MainForma;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class KreiranjeFilmForma extends javax.swing.JDialog {

    List<Glumac> glumci = new ArrayList<>();

    /**
     * Creates new form KreirajFilmDijalog
     */
    public KreiranjeFilmForma(JDialog owner) {
        super(owner);
        initComponents();
        prepareView();
        btnDodajFilm.setVisible(false);
        setLocationRelativeTo(null);
    }

    public KreiranjeFilmForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareView();
        btnKreirajFilm.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTrajanjeFilma = new javax.swing.JTextField();
        txtDrzavaPorekla = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbdZanr = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDodajFilm = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNazivFilma = new javax.swing.JTextField();
        txtDatumIzlaska = new javax.swing.JTextField();
        cbdReziser = new javax.swing.JComboBox();
        btnKreirajFilm = new javax.swing.JButton();
        cbdGlumac = new javax.swing.JComboBox();
        lblGlumci = new javax.swing.JLabel();
        btnDodajGlumca = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblDodatiGlumci = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos novog filma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N

        jLabel1.setText("Naziv filma: ");

        cbdZanr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Datum izlaska: ");

        jLabel3.setText("Trajanje filma:");

        btnDodajFilm.setText("Dodaj film");
        btnDodajFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajFilmActionPerformed(evt);
            }
        });

        jLabel4.setText("Drzava porekla:");

        jLabel5.setText("Zanr:");

        jLabel6.setText("Reziser: ");

        cbdReziser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnKreirajFilm.setText("Kreiraj film");
        btnKreirajFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajFilmActionPerformed(evt);
            }
        });

        cbdGlumac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblGlumci.setText("Glumci:");

        btnDodajGlumca.setText("Dodaj glumca");
        btnDodajGlumca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajGlumcaActionPerformed(evt);
            }
        });

        jLabel7.setText("Dodati glumci: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDodajFilm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKreirajFilm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(lblGlumci)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNazivFilma)
                            .addComponent(txtTrajanjeFilma)
                            .addComponent(cbdZanr, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbdReziser, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDrzavaPorekla)
                            .addComponent(txtDatumIzlaska)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbdGlumac, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDodajGlumca)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblDodatiGlumci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivFilma, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDatumIzlaska, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrajanjeFilma, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDrzavaPorekla, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbdZanr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbdReziser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbdGlumac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGlumci)
                    .addComponent(btnDodajGlumca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDodatiGlumci, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajFilm)
                    .addComponent(btnKreirajFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajFilmActionPerformed
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy");
            String nazivFilma = txtNazivFilma.getText().trim();
            Date datumIzlaska = format.parse(txtDatumIzlaska.getText().trim());
            int trajanjeFilma = Integer.parseInt(txtTrajanjeFilma.getText().trim());
            String drzavaPorekla = txtDrzavaPorekla.getText().trim();
            Zanr zanr = (Zanr) cbdZanr.getSelectedItem();
            Reziser reziser = (Reziser) cbdReziser.getSelectedItem();
            MainForma mn = (MainForma) getParent();
            Film noviFilm = new Film(-1l, nazivFilma, datumIzlaska, trajanjeFilma, drzavaPorekla, null, zanr, reziser, glumci);
            validate(noviFilm);
            communication.Communication.getInstance().saveFilm(noviFilm);
            JOptionPane.showMessageDialog(this, "Uspešno sacuvan film!", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Datum mora biti u formatu dd.mm.gggg!", "Greska", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Trajanje filma mora biti broj!", "Greska", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnDodajFilmActionPerformed

    private void btnKreirajFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajFilmActionPerformed
//        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy");
//        String nazivFilma = txtNazivFilma.getText().trim();
//        Date datumIzlaska = new Date();
//        try {
//            datumIzlaska = format.parse(txtDatumIzlaska.getText().trim());
//        } catch (ParseException ex) {
//            JOptionPane.showMessageDialog(this, "Datum mora biti u formatu dd.mm.gggg!");
//        }
//        int trajanjeFilma = Integer.parseInt(txtTrajanjeFilma.getText().trim());
//        String drzavaPorekla = txtDrzavaPorekla.getText().trim();
//        Zanr zanr = (Zanr) cbdZanr.getSelectedItem();
//        Reziser reziser = (Reziser) cbdReziser.getSelectedItem();
//        KreiranjeListeForma mn = (KreiranjeListeForma) getOwner();
//
//        Film noviFilm = new Film(-1l, nazivFilma, datumIzlaska, trajanjeFilma, drzavaPorekla, null, zanr, reziser, glumci);
//
//        mn.addFilm(noviFilm);
//        this.dispose();
    }//GEN-LAST:event_btnKreirajFilmActionPerformed

    private void btnDodajGlumcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajGlumcaActionPerformed
        Glumac glumac = (Glumac) cbdGlumac.getSelectedItem();
        if (glumci.contains(glumac)) {
            JOptionPane.showMessageDialog(this, "Glumac je već dodat!");
        } else {
            if (glumci.size() == 0) {
                lblDodatiGlumci.setText("" + glumac);
            } else {
                lblDodatiGlumci.setText(lblDodatiGlumci.getText() + ", " + glumac);
            }
            glumci.add(glumac);

        }

    }//GEN-LAST:event_btnDodajGlumcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreiranjeFilmForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreiranjeFilmForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreiranjeFilmForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreiranjeFilmForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajFilm;
    private javax.swing.JButton btnDodajGlumca;
    private javax.swing.JButton btnKreirajFilm;
    private javax.swing.JComboBox cbdGlumac;
    private javax.swing.JComboBox cbdReziser;
    private javax.swing.JComboBox cbdZanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDodatiGlumci;
    private javax.swing.JLabel lblGlumci;
    private javax.swing.JTextField txtDatumIzlaska;
    private javax.swing.JTextField txtDrzavaPorekla;
    private javax.swing.JTextField txtNazivFilma;
    private javax.swing.JTextField txtTrajanjeFilma;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        try {
            List<Zanr> zanrovi = Communication.getInstance().getZanrovi();
            List<Reziser> reziseri = Communication.getInstance().getReziseri();
            List<Glumac> glumci = Communication.getInstance().getGlumci();
            cbdReziser.removeAllItems();
            cbdZanr.removeAllItems();
            cbdGlumac.removeAllItems();
            for (Reziser reziser : reziseri) {
                cbdReziser.addItem(reziser);
            }
            for (Zanr zanr : zanrovi) {
                cbdZanr.addItem(zanr);
            }
            for (Glumac glumac : glumci) {
                cbdGlumac.addItem(glumac);
            }
            cbdGlumac.setSelectedItem(null);
            cbdReziser.setSelectedItem(null);
            cbdZanr.setSelectedItem(null);
        } catch (Exception ex) {
            Logger.getLogger(KreiranjeFilmForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void validate(Film film) throws Exception {
        String message = "";
        if (film.getNaziv().isBlank()) {
            message += "Unesite naziv\n";
        }
        if (film.getTrajajanjeFilma() < 0) {
            message += "Unesite ispravno trajanje filma\n";
        }
        if (film.getDrzavaPorekla().isBlank()) {
            message += "Unesite drzavu porekla\n";
        }
        if (film.getZanr() == null) {
            message += "Selektujte Zanr\n";
        }
        if (film.getReziser() == null) {
            message += "Selektujte Rezisera\n";
        }
        if (film.getGlumci().isEmpty()) {
            message += "Dodajte glumce\n";
        }
        if(!message.equals(""))
            throw new Exception(message);
    }
}
